// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data;

#nullable disable

namespace QuanLyQuanNet.Migrations
{
    [DbContext(typeof(ProjetcNetQuanLyMayTinhContext))]
    [Migration("20250413095508_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Project.Data.MayTinh", b =>
                {
                    b.Property<string>("MaMay")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("MaMay");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<string>("TenMay")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ThoiGianXoa")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("MaMay");

                    b.ToTable("MayTinh");
                });

            modelBuilder.Entity("Project.Data.NapTien", b =>
                {
                    b.Property<string>("MaNapTien")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaNguoiDungNavigationMaNguoiDung")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("ThoiGianNap")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MaNapTien");

                    b.HasIndex("MaNguoiDungNavigationMaNguoiDung");

                    b.ToTable("NapTiens");
                });

            modelBuilder.Entity("Project.Data.NguoiDung", b =>
                {
                    b.Property<string>("MaNguoiDung")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayTaoTaiKhoan")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("NgayXoaTaiKhoan")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("SoDu")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TrangThai")
                        .HasColumnType("longtext");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("Project.Data.SuDungMay", b =>
                {
                    b.Property<string>("MaSuDung")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaMay")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaMayNavigationMaMay")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaNguoiDung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaNguoiDungNavigationMaNguoiDung")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("TongThoiGian")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("MaSuDung");

                    b.HasIndex("MaMayNavigationMaMay");

                    b.HasIndex("MaNguoiDungNavigationMaNguoiDung");

                    b.ToTable("SuDungMays");
                });

            modelBuilder.Entity("Project.Data.NapTien", b =>
                {
                    b.HasOne("Project.Data.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("NapTiens")
                        .HasForeignKey("MaNguoiDungNavigationMaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("Project.Data.SuDungMay", b =>
                {
                    b.HasOne("Project.Data.MayTinh", "MaMayNavigation")
                        .WithMany("SuDungMays")
                        .HasForeignKey("MaMayNavigationMaMay");

                    b.HasOne("Project.Data.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("SuDungMays")
                        .HasForeignKey("MaNguoiDungNavigationMaNguoiDung");

                    b.Navigation("MaMayNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("Project.Data.MayTinh", b =>
                {
                    b.Navigation("SuDungMays");
                });

            modelBuilder.Entity("Project.Data.NguoiDung", b =>
                {
                    b.Navigation("NapTiens");

                    b.Navigation("SuDungMays");
                });
#pragma warning restore 612, 618
        }
    }
}
